-- MySQL Script generated by MySQL Workbench
-- Thu Nov  9 12:36:11 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Tapete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tapete` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(8) NULL,
  `rua` VARCHAR(80) NULL,
  `cidade` VARCHAR(45) NULL,
  `uf` VARCHAR(2) NULL,
  `referencia` VARCHAR(150) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sexo` VARCHAR(1) NOT NULL,
  `idadeIni` VARCHAR(2) NULL,
  `idadeFim` VARCHAR(2) NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Percurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Percurso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `itinerario` VARCHAR(300) NULL,
  `distancia` INT NULL,
  `Categoria_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Percurso_Categoria1_idx` (`Categoria_id` ASC),
  CONSTRAINT `fk_Percurso_Categoria1`
    FOREIGN KEY (`Categoria_id`)
    REFERENCES `mydb`.`Categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Corrida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Corrida` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `localLargada` VARCHAR(100) NULL,
  `localChegada` VARCHAR(100) NULL,
  `horaLargada` VARCHAR(10) NULL,
  `duracaoLim` INT NULL,
  `dataCorrida` VARCHAR(10) NULL,
  `dataRetiradaKit` VARCHAR(10) NULL,
  `localRetiradaKit` VARCHAR(100) NULL,
  `numMaxInscritos` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`List_Tapetes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`List_Tapetes` (
  `Percurso_id` INT NOT NULL,
  `Tapete_id` INT NOT NULL,
  INDEX `fk_List_Tapetes_Tapete1_idx` (`Tapete_id` ASC),
  INDEX `fk_List_Tapetes_Percurso1_idx` (`Percurso_id` ASC),
  PRIMARY KEY (`Percurso_id`),
  CONSTRAINT `fk_List_Tapetes_Tapete1`
    FOREIGN KEY (`Tapete_id`)
    REFERENCES `mydb`.`Tapete` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_List_Tapetes_Percurso1`
    FOREIGN KEY (`Percurso_id`)
    REFERENCES `mydb`.`Percurso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`List_Percurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`List_Percurso` (
  `Corrida_id` INT NOT NULL,
  `Percurso_id` INT NOT NULL,
  INDEX `fk_List_Percurso_Corrida1_idx` (`Corrida_id` ASC),
  INDEX `fk_List_Percurso_Percurso1_idx` (`Percurso_id` ASC),
  PRIMARY KEY (`Corrida_id`),
  CONSTRAINT `fk_List_Percurso_Corrida1`
    FOREIGN KEY (`Corrida_id`)
    REFERENCES `mydb`.`Corrida` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_List_Percurso_Percurso1`
    FOREIGN KEY (`Percurso_id`)
    REFERENCES `mydb`.`Percurso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ranking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ranking` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Corrida_id` INT NOT NULL,
  `Categoria_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Ranking_Categoria1_idx` (`Categoria_id` ASC),
  CONSTRAINT `fk_Ranking_Corrida1`
    FOREIGN KEY (`Corrida_id`)
    REFERENCES `mydb`.`Corrida` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ranking_Categoria1`
    FOREIGN KEY (`Categoria_id`)
    REFERENCES `mydb`.`Categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lote` (
  `id` INT NOT NULL,
  `preco` DOUBLE NULL,
  `dataLimite` VARCHAR(10) NULL,
  `Corrida_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Lote_Corrida1_idx` (`Corrida_id` ASC),
  CONSTRAINT `fk_Lote_Corrida1`
    FOREIGN KEY (`Corrida_id`)
    REFERENCES `mydb`.`Corrida` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `dataNasc` VARCHAR(10) NULL,
  `sexo` TINYINT NULL,
  `tel_cel` VARCHAR(14) NULL,
  `tel_res` VARCHAR(14) NULL,
  `cep` VARCHAR(8) NULL,
  `rua` VARCHAR(80) NULL,
  `uf` VARCHAR(2) NULL,
  `cidade` VARCHAR(45) NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Atleta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Atleta` (
  `Usuario_cpf` VARCHAR(11) NOT NULL,
  `pace` INT NOT NULL,
  `apelido` VARCHAR(45) NULL,
  `email` VARCHAR(60) NULL,
  `senha` VARCHAR(45) NULL,
  PRIMARY KEY (`Usuario_cpf`),
  CONSTRAINT `fk_Atleta_Usuario1`
    FOREIGN KEY (`Usuario_cpf`)
    REFERENCES `mydb`.`Usuario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Camisa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Camisa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tamanho` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Chip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Chip` (
  `numero` INT NOT NULL AUTO_INCREMENT,
  `tempoCorrida` TIME NULL,
  `Percurso_id` INT NOT NULL,
  PRIMARY KEY (`numero`),
  INDEX `fk_Chip_Percurso1_idx` (`Percurso_id` ASC),
  CONSTRAINT `fk_Chip_Percurso1`
    FOREIGN KEY (`Percurso_id`)
    REFERENCES `mydb`.`Percurso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Camisa_id` INT NOT NULL,
  `Chip_numero` INT NOT NULL,
  INDEX `fk_Kit_Camisa1_idx` (`Camisa_id` ASC),
  INDEX `fk_Kit_Chip1_idx` (`Chip_numero` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Kit_Camisa1`
    FOREIGN KEY (`Camisa_id`)
    REFERENCES `mydb`.`Camisa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Kit_Chip1`
    FOREIGN KEY (`Chip_numero`)
    REFERENCES `mydb`.`Chip` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ingresso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ingresso` (
  `num_inscricao` INT NOT NULL,
  `Lote_id` INT NOT NULL,
  `Atleta_Usuario_cpf` VARCHAR(11) NOT NULL,
  `Kit_id` INT NOT NULL,
  PRIMARY KEY (`num_inscricao`),
  INDEX `fk_Ingresso_Lote1_idx` (`Lote_id` ASC),
  INDEX `fk_Ingresso_Atleta1_idx` (`Atleta_Usuario_cpf` ASC),
  INDEX `fk_Ingresso_Kit1_idx` (`Kit_id` ASC),
  CONSTRAINT `fk_Ingresso_Lote1`
    FOREIGN KEY (`Lote_id`)
    REFERENCES `mydb`.`Lote` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ingresso_Atleta1`
    FOREIGN KEY (`Atleta_Usuario_cpf`)
    REFERENCES `mydb`.`Atleta` (`Usuario_cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ingresso_Kit1`
    FOREIGN KEY (`Kit_id`)
    REFERENCES `mydb`.`Kit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Administrador` (
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NULL,
  `Usuario_cpf` VARCHAR(11) NOT NULL,
  INDEX `fk_Administrador_Usuario1_idx` (`Usuario_cpf` ASC),
  PRIMARY KEY (`email`),
  CONSTRAINT `fk_Administrador_Usuario1`
    FOREIGN KEY (`Usuario_cpf`)
    REFERENCES `mydb`.`Usuario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Organizador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Organizador` (
  `Usuario_cpf` VARCHAR(11) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `senha` VARCHAR(45) NULL,
  PRIMARY KEY (`Usuario_cpf`),
  CONSTRAINT `fk_Organizador_Usuario1`
    FOREIGN KEY (`Usuario_cpf`)
    REFERENCES `mydb`.`Usuario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pagamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `preco` INT NOT NULL,
  `metodoPag` VARCHAR(1) NULL,
  `Ingresso_num_inscricao` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Pagamento_Ingresso1_idx` (`Ingresso_num_inscricao` ASC),
  CONSTRAINT `fk_Pagamento_Ingresso1`
    FOREIGN KEY (`Ingresso_num_inscricao`)
    REFERENCES `mydb`.`Ingresso` (`num_inscricao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CartaoCredito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CartaoCredito` (
  `numero` VARCHAR(20) NOT NULL,
  `bandeira` VARCHAR(20) NULL,
  `nomeTitular` VARCHAR(45) NULL,
  `cpfTitular` VARCHAR(11) NULL,
  `dataValidade` VARCHAR(10) NULL,
  `codSeguranca` VARCHAR(5) NULL,
  `numParcelas` INT NULL,
  `valorParcelas` DOUBLE NULL,
  `Pagamento_id` INT NOT NULL,
  PRIMARY KEY (`numero`),
  INDEX `fk_CartaoCredito_Pagamento1_idx` (`Pagamento_id` ASC),
  CONSTRAINT `fk_CartaoCredito_Pagamento1`
    FOREIGN KEY (`Pagamento_id`)
    REFERENCES `mydb`.`Pagamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Boleto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Boleto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(11) NOT NULL,
  `nomeCliente` VARCHAR(45) NULL,
  `Pagamento_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Boleto_Pagamento1_idx` (`Pagamento_id` ASC),
  CONSTRAINT `fk_Boleto_Pagamento1`
    FOREIGN KEY (`Pagamento_id`)
    REFERENCES `mydb`.`Pagamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
